block_worker: https://dev.0chain.net/dns
# block_worker: https://dev.0chain.net/dns
signature_scheme: bls0chain
min_submit: 50 # in percentage
min_confirmation: 50 # in percentage
confirmation_chain_length: 3
max_txn_query: 15
query_sleep_time: 2