name: 0Chain System Tests Nightly
on:
  schedule:
    # Runs everyday at 4:10 am
    - cron: '10 4 * * * '
  workflow_dispatch:
jobs:
  network-liveness-check:
    strategy:
      matrix:
        network: [ "beta.0chain.net", "dev.0chain.net", "test.0chain.net" ]
    runs-on: self-hosted
    steps:
      - name: "Check 0Proxy Liveness"
        run: curl --silent --show-error --fail --max-time 10 https://${{ matrix.network }}/dns

      - name: "Check Explorer Liveness"
        run: curl --silent --show-error --fail --max-time 10 https://${{ matrix.network }}

      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: "Configure node"
        run: |
          npm config set user 0
          npm config set unsafe-perm true

      - name: "Install Newman"
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: "Run Smoke Tests"
        run: |
          cd tests/api_tests
          custom_network=$(echo ${{ matrix.network }} | xargs | sed -E 's/^\s*.*:\/\///g' | sed 's:/*$::') && sed -i "0,/REPLACE/s//$custom_network/" './Postman Collections/Environments/custom.postman_environment.json'
          newman run "./0chain-smoke-test.json" -e "./Environments/custom.postman_environment.json" -r cli --color on
  s3Backup:
    runs-on: docker-builds
    steps:
      - uses: actions/checkout@v1
      - name: Create backup
        run: |
          github-backup 0chain -P -t ${{ secrets.ACCESS_TOKEN }} --output-directory=/github-backup/system_test --all -O -R system_test
      - name: Create zip
        run: zip -r system_test.zip /github-backup/system_test
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Backup to s3
        run: |
          aws s3 cp system_test.zip s3://${{ secrets.MIRROR_TARGET }}/system_test.zip