name: 0Chain Network Health Check
on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  network-health-check:
    runs-on: self-hosted
    strategy:
      matrix:
        network: [ "beta.0chain.net", "demo.0chain.net", "dev.0chain.net", "huawei.0chain.net", "polygon.0chain.net", "test.0chain.net" ]
      fail-fast: false
    steps:
      - name: "Run Smoke Tests"
        run: |
          echo "${{ secrets.DEVOPS_CHANNEL_WEBHOOK_URL }}" >> webhook.properties

      - name: "Archive"
        uses: actions/upload-artifact@v2
        with:
          name: webhook.properties
          path: |
            ./webhook.properties