name: 0Chain Nightly Network Check
on:
  workflow_dispatch:
jobs:
  network-liveness-check:
    strategy:
      matrix:
        network: [ "beta.0chain.net", "dev.0chain.net", "test.0chain.net" ]
    runs-on: self-hosted
    steps:
      - name: "Placeholder"
        run: echo ${{ matrix.network }}